#!/bin/sh

function _command_exists() {
  hash "$1" 2>/dev/null
}

if _command_exists brew; then
  echo 'brew already install!!'
else
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew tap Homebrew/bundle

brew bundle --file=$HOME/.inkaku/Brewfile

if [ ! $(grep -w "/usr/local/bin/zsh" /etc/shells) ]; then
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
fi

chsh -s /usr/local/bin/zsh

chmod +x ~/.inkaku/bin/inkaku

~/.inkaku/bin/inkaku init

~/.inkaku/bin/inkaku install ${USER}

if [ ! $(grep -w 'source ~/.inkaku/.zshrc' $HOME/.zshrc) ]; then
  echo 'source ~/.inkaku/.zshrc' >> $HOME/.zshrc
fi
