#!/bin/sh

function _command_exists() {
  hash "$1" 2>/dev/null
}

if _command_exists brew; then
  echo 'brew already install!!'
else
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew tap Homebrew/bundle

brew bundle --file=$HOME/.inkaku/Brewfile

if [ -f ${HOME}/.inkaku/${USER}/Brewfile ]; then
  brew bundle --file=${HOME}/.inkaku/${USER}/Brewfile
fi

if [ -f ${HOME}/.inkaku/${USER}/install ]; then
  zsh ${HOME}/.inkaku/${USER}/install
fi

echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells

chsh -s /usr/local/bin/zsh

echo 'source $HOME/.inkaku/inkaku.zsh' >> $HOME/.zshrc
mkdir -p $HOME/.inkaku/zsh
